"""Initial schema.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-17

The baseline schema is created from the SQLAlchemy metadata rather than being
transcribed by hand. That keeps the models and the initial migration from
drifting apart on day one; every *subsequent* migration is an ordinary
autogenerated diff against this baseline.

On top of the tables this migration installs the things the ORM cannot express:

* TimescaleDB hypertables for ``candles`` and ``ticks``, plus a retention policy
  on raw ticks (DB-005, DB-006).
* Append-only triggers on ``audit_events`` and ``config_changes`` so tampering
  fails at the database, not merely by application convention (DB-012).
* A cross-row trigger asserting that fills never exceed their order's quantity
  (DB-008) — a constraint that cannot be written as a per-row CHECK.
* A singleton constraint on ``system_state`` (DB-018).
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.db.models import metadata as target_metadata

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: The tables that existed at baseline, pinned by name. ``create_all`` is scoped to
#: this list so that adding a model later does not retroactively change what this
#: migration creates — every later change is its own incremental migration.
BASELINE_TABLES = (
    "audit_events",
    "backtest_results",
    "backtest_runs",
    "backtest_trades",
    "candles",
    "config_changes",
    "considered_candidates",
    "corporate_events",
    "discrepancies",
    "fundamentals",
    "health_records",
    "heartbeats",
    "instruments",
    "journal_annotations",
    "journal_entries",
    "llm_calls",
    "news_items",
    "news_sources",
    "option_chain_snapshots",
    "order_events",
    "orders",
    "portfolio_snapshots",
    "positions",
    "proposals",
    "risk_config_versions",
    "risk_decisions",
    "sizing_records",
    "strategy_registrations",
    "system_state",
    "ticks",
    "trades",
)


REFUSE_MUTATION_FN = """
CREATE OR REPLACE FUNCTION ats_refuse_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        'table % is append-only; % is not permitted', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'check_violation';
END;
$$ LANGUAGE plpgsql;
"""

CHECK_FILL_SUM_FN = """
CREATE OR REPLACE FUNCTION ats_check_fill_sum() RETURNS trigger AS $$
DECLARE
    other_fills integer;
    ordered_quantity integer;
BEGIN
    SELECT COALESCE(SUM(quantity), 0) INTO other_fills
        FROM trades WHERE order_id = NEW.order_id AND id <> NEW.id;
    SELECT quantity INTO ordered_quantity FROM orders WHERE id = NEW.order_id;

    IF ordered_quantity IS NOT NULL
       AND other_fills + NEW.quantity > ordered_quantity THEN
        RAISE EXCEPTION
            'fills for order % would total % but the order is only for %',
            NEW.order_id, other_fills + NEW.quantity, ordered_quantity
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

TIMESCALE_SETUP = """
DO $$
BEGIN
    BEGIN
        CREATE EXTENSION IF NOT EXISTS timescaledb;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE
            'TimescaleDB extension unavailable (%); candles and ticks remain plain tables',
            SQLERRM;
        RETURN;
    END;

    PERFORM create_hypertable('candles', 'ts',
        if_not_exists => TRUE, migrate_data => TRUE, chunk_time_interval => INTERVAL '7 days');
    PERFORM create_hypertable('ticks', 'ts',
        if_not_exists => TRUE, migrate_data => TRUE, chunk_time_interval => INTERVAL '1 day');

    BEGIN
        PERFORM add_retention_policy('ticks', INTERVAL '90 days', if_not_exists => TRUE);
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Could not add retention policy on ticks: %', SQLERRM;
    END;
END
$$;
"""


def _baseline_tables() -> list:
    missing = [name for name in BASELINE_TABLES if name not in target_metadata.tables]
    if missing:
        raise RuntimeError(
            f"baseline tables are no longer defined by the models: {missing}. "
            f"A renamed or removed baseline table needs its own migration."
        )
    return [target_metadata.tables[name] for name in BASELINE_TABLES]


def upgrade() -> None:
    bind = op.get_bind()
    target_metadata.create_all(bind=bind, tables=_baseline_tables())

    if bind.dialect.name != "postgresql":
        # SQLite is used for fast model-level tests; the PostgreSQL-specific
        # guarantees below are exercised by the integration suite.
        return

    op.execute(REFUSE_MUTATION_FN)
    for table in ("audit_events", "config_changes"):
        op.execute(
            f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION ats_refuse_mutation();
            """
        )

    op.execute(CHECK_FILL_SUM_FN)
    op.execute(
        """
        CREATE TRIGGER trades_fill_sum
        BEFORE INSERT OR UPDATE ON trades
        FOR EACH ROW EXECUTE FUNCTION ats_check_fill_sum();
        """
    )

    op.execute(
        """
        ALTER TABLE system_state
        ADD CONSTRAINT ck_system_state_singleton CHECK (id = 'singleton');
        """
    )

    op.execute(TIMESCALE_SETUP)


def downgrade() -> None:
    bind = op.get_bind()

    if bind.dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS trades_fill_sum ON trades;")
        op.execute("DROP TRIGGER IF EXISTS audit_events_append_only ON audit_events;")
        op.execute("DROP TRIGGER IF EXISTS config_changes_append_only ON config_changes;")
        op.execute("DROP FUNCTION IF EXISTS ats_check_fill_sum();")
        op.execute("DROP FUNCTION IF EXISTS ats_refuse_mutation();")

    target_metadata.drop_all(bind=bind, tables=_baseline_tables())
    # Enum types are not dropped by drop_all on PostgreSQL.
    if bind.dialect.name == "postgresql":
        for enum_name in sorted(
            {
                t.name
                for table in _baseline_tables()
                for t in (column.type for column in table.columns)
                if isinstance(t, sa.Enum) and t.name
            }
        ):
            op.execute(f"DROP TYPE IF EXISTS {enum_name} CASCADE;")
