import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';

const browser = await chromium.launch({ channel: process.env.ATS_BROWSER_CHANNEL || 'msedge', headless: true });
const option = process.env.ATS_TEST_HISTORICAL_KIND === 'OPTION';
const netPnl = option ? '-27.93' : '856.56';
const strategy = option ? 'long-option-breakout' : 'closed-candle-breakout';
try {
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.argv[2]);
  await page.getByLabel('Username', { exact: true }).fill('owner');
  await page.getByLabel('Password', { exact: true }).fill(process.env.ATS_TEST_OWNER_PASSWORD);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  const listing = page.waitForResponse(response => response.url().includes('/api/v1/backtests?'));
  const plansResponse = page.waitForResponse(response => response.url().endsWith('/api/v1/historical-jobs/plans'));
  await page.getByRole('button', { name: 'Backtests', exact: true }).click();
  const response = await listing;
  assert.equal(response.status(), 200, await response.text());
  assert.equal((await response.json()).runs.length, 0);
  const plans = await plansResponse;
  assert.equal(plans.status(), 200, await plans.text());
  assert.equal((await plans.json())[0]?.id, 'fixture01');
  await page.getByLabel('Historical plan', { exact: true }).selectOption('fixture01');
  await page.getByLabel('Research reason', { exact: true }).fill('Isolated browser fixture research');
  await page.getByLabel('Type RUN HISTORICAL PAPER', { exact: true }).fill('RUN HISTORICAL PAPER');
  const launched = page.waitForResponse(response => response.url().endsWith('/api/v1/historical-jobs') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Launch isolated PAPER research', exact: true }).click();
  const launchResponse = await launched;
  assert.equal(launchResponse.status(), 202);
  assert.equal((await launchResponse.json()).simulated, true);
  const selected = page.getByLabel('Historical run', { exact: true });
  await selected.locator('option[value="fixture01"]').waitFor({ state: 'attached' });
  await selected.selectOption('fixture01');
  await page.getByRole('heading', { name: 'COMPLETED — 100.000000%' }).waitFor();
  await page.getByRole('img', { name: 'Sampled net equity', exact: true }).waitFor();
  await page.getByRole('img', { name: 'Sampled drawdown fraction', exact: true }).waitFor();
  await page.getByRole('cell', { name: netPnl, exact: true }).waitFor();
  await page.getByText(`Strategy: ${strategy} / version 1`, { exact: true }).waitFor();
  assert.match(await page.locator('main').innerText(), /RECORDED_DEPTH_AT_PUBLICATION/);
  const universe = page.getByRole('region', { name: 'Universe construction' });
  assert.match(await universe.innerText(), /OWNER_DECLARED_STATIC_LISTS/);
  assert.match(await universe.innerText(), /Survivorship and selection bias remain possible/);
  await universe.locator('summary').first().click();
  assert.match(await universe.innerText(), /STRATEGY_INSTRUMENT/);
  assert.match(await universe.innerText(), /CONTEXT_ONLY/);
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export simulated report JSON', exact: true }).click();
  const download = await downloadEvent;
  assert.equal(download.suggestedFilename(), 'simulated-backtest.json');
  const stream = await download.createReadStream();
  const chunks = [];
  for await (const chunk of stream) chunks.push(chunk);
  const exported = JSON.parse(Buffer.concat(chunks).toString('utf8'));
  assert.equal(exported.simulated, true);
  assert.equal(exported.catalog_integrity, 'AUDIT_BOUND');
  assert.equal(exported.universe_disclosure.method, 'OWNER_DECLARED_STATIC_LISTS');
  assert.equal(exported.run.strategy_id, strategy);
  assert.equal(exported.run.strategy_version, '1');
  assert.equal(exported.window_disclosure.windows[0].elapsed_seconds, '5');
  assert.equal(exported.window_disclosure.windows[0].span_state, 'BELOW_MINIMUM');
  assert.equal(exported.window_disclosure.windows[0].minimum_calendar_days, 60);
  assert.equal(exported.window_disclosure.windows[0].continuous_coverage_verified, false);
  assert.match(await page.getByRole('region', { name: 'Historical window adequacy' }).innerText(), /BELOW_MINIMUM/);
  assert.equal(exported.trades[0].net_pnl, netPnl);
  if (option) {
    assert.equal(exported.results[0].gross_pnl, '-16.00');
    assert.equal(exported.results[0].total_charges, '11.93');
    assert.equal(exported.results[0].net_pnl, netPnl);
  }
  assert.match(await page.locator('main').innerText(), /Reproducibility fingerprints: v1; inputs [a-f0-9]{64}; outcomes [a-f0-9]{64}/);
  assert.match(await page.locator('main').innerText(), /UNAVAILABLE/);
  await page.getByText(/fixture01: COMPLETED.*REPORT PUBLISHED/).waitFor();
  await page.reload();
  await page.getByRole('button', { name: 'Backtests', exact: true }).click();
  await page.getByLabel('Historical run', { exact: true }).selectOption('fixture01');
  await page.getByRole('cell', { name: netPnl, exact: true }).waitFor();
  await page.getByRole('img', { name: 'Sampled drawdown fraction', exact: true }).waitFor();
  const workspaceResult = page.waitForResponse(response => response.url().endsWith('/api/v1/workspace'));
  await page.getByRole('button', { name: 'Dashboard', exact: true }).click();
  const workspaceResponse = await workspaceResult;
  assert.equal(workspaceResponse.status(), 200);
  const workspace = await workspaceResponse.json();
  assert.equal(workspace.orders.length, 0);
  assert.equal(workspace.positions.length, 0);
  assert.deepEqual(errors, []);
  process.stdout.write('HISTORICAL_VERIFIED\n');
} finally { await browser.close(); }
